/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sequality;

public class App {
  public String FbCounter(int x) {
    int f = 0;
    int b = 0;
    int fb = 0;
    String f_str = "";
    String b_str = "";
    String fb_str = "";

    for (int i = 1; i <= x; i++) {
      if (i % 15 == 0) {
        fb = fb + 1;
      } else if (i % 3 == 0) {
        f = f + 1;
      } else if (i % 5 == 0) {
        b = b + 1;
      } else {
        continue;
      }
    }

    f_str = Integer.valueOf(f).toString();
    b_str = Integer.valueOf(b).toString();
    fb_str = Integer.valueOf(fb).toString();

    return "Fizz: " + f_str + ", Buzz: " + b_str + ", FizzBuzz: " + fb_str;
  }

  public String f1() {
    String r;
    r = FbCounter(6);
    return r;
  }

  public String f2() {
    String r;
    r = FbCounter(10);
    return r;
  }

  public String f3() {
    String r;
    r = FbCounter(30);
    return r;
  }

  public String f4() {
    String r;
    r = FbCounter(1);
    return r;
  }

  public static void main(String[] args) {
    System.out.println(new App().f1());
    System.out.println(new App().f2());
    System.out.println(new App().f3());
    System.out.println(new App().f4());
  }
}
